[package]
name = "thruster"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29.1"
egui = "0.29.1"
image = "0.25.5"
itertools = "0.13.0"
open = "5.3.0"
rfd = "0.15.1"
scraper = "0.20.0"
